### ISSUE TITLE
Kernel interrupt doesn't work on Windows with Python 3.7

### ISSUE THREAD

**Issue by tom-bowles** [jupyter/jupyter_client#387]
In a Jupyter notebook with Python 3.7, if I run a "while True: pass" infinite loop and try to interrupt it with Kernel -> Interrupt, the server's stdout says the kernel has been interrupted but the loop doesn't stop. This works with Python 3.6.6.

I've raised the issue on this project because I suspect the problem is to do with changes in Python 3.7 in the way handles are/aren't inherited on Windows - see https://www.python.org/dev/peps/pep-0446/ and https://bugs.python.org/issue19764. I think some kind of extra work is going to be needed to get the interrupt event handle to be inherited by the child process and therefore I think the fix is most likely to be in jupyter_client, but I haven't managed to get it working myself.

**Comment by metya** [comment]
same problem in jupyter lab on python 3.7 kernel

**Comment by minrk** [comment]
Fixed by #408, released as jupyter-client 5.2.4

**Comment by angelopolotto** [comment]
I having this problem in the Windows 10 with Jupyter 5.7.8 and with JupterLab 0.35.4 both running on Anaconda Navigator. Seems not solved for me. Anybody know if this can be a configuration problem?

**Comment by carlotaSG** [comment]
I am still having this same issue in Windows 10 running jupyter notebook from Anaconda. My jupyter-client is a newer version than 5.2.4 - any ideas on how to solve this?
![image](https://user-images.githubusercontent.com/58551165/113407320-f2a8cb00-93a4-11eb-81fe-0c9bce5100c1.png)

**Comment by kevin-bates** [comment]
Do you know if you're using [`nb_conda_kernels`](https://github.com/Anaconda-Platform/nb_conda_kernels) or not?  I believe there can be some issues with interrupt propagation on Windows when running a kernel in an environment other than the one in which `jupyter_client` resides.

If you're using NB Conda Kernels, your kernel names should have some bracketed information pertaining to the configured conda envs, IIRC.
